; docker/php-extra.ini
display_errors = Off
log_errors = On
error_log = /dev/stderr
expose_php = Off
output_buffering = 4096
session.use_strict_mode = 1
session.cookie_httponly = 1
session.cookie_samesite = Lax
